### PR TITLE
Support for seach and thumbnails

### PR DESCRIPTION
**Pull request by holm**
I needed to extend the client to support search and thumbnails. As I was using the client for the first time I also discovered some inconsistencies in the returned values. Sometimes it was the response object, sometimes the json object. It lead me down a bit of a rabbithole and I ended up moving quite a few things around (and more than once). I am personally fairly happy with the current state of it, but it is probably a bit opinionated. 

I should really have made more separate pull requests, but since I was in a hurry to get the changes done for Podio, I wasn't very organized in my changes. 

So take it, parts of it, or reject it, it's all up to you :)

### CODE REVIEW

**Comment by tals** [comment]
These are really good! Thank you!

A few things though:
- The tests are broken (see test_authentication.py). You can also run these with `nosetests`
- Make sure coverage is still at 100% (nosetests should display it at the bottom) :)

**Comment by tals** [comment]
Also, `refresh()` & `_request()` & `CredentialsV2.__init__()` are missing documentation :)

Other than that, it's really really nice. Thank you!

**Comment by holm** [comment]
Sorry about, I should have spent more time on it. It should all pass now and have 100% coverage. I will work on the documentation also.

**Comment by tals** [comment]
:+1: 
There are a few little things left (flake8 is raising some pep8 warnings, and readme.MD needs updating), but I can take care of those :)

Should I merge, or do you want to add something else? :)

**Comment by holm** [comment]
I am all done, thanks!

**Comment by tals** [comment]
You rock :)

**Comment by tals** [comment]
(I'll do a pypi push after I'll update the docs)

**Comment by tals** [comment]
Ha, just saw the pep8 patch. Open a new PR? :P

**Comment by holm** [comment]
Yeah, it's here: https://github.com/sookasa/box.py/pull/3

**Pull request merged**
