### PR TITLE
- Comments, Tasks and Assignments support

### PR DESCRIPTION
**Pull request by tsanch3z**
I've added the comments, tasks and assignments support.

### CODE REVIEW

**Comment by tals** [comment]
Thanks!
Can you add tests though? See tests/test_client.py

Also, there are a few odd whitespacing issues (lines 115, 353, 371 at box/client.py), although I can fix those later.

**Comment by tsanch3z** [comment]
I'll try to add tests and remove white spaces by the end of week

**Comment by tals** [comment]
Cool :)

**Comment by tsanch3z** [comment]
It should be done :)

**Comment by tals** [comment]
Awesome! Thank you!

**Pull request merged**
