### PR TITLE
support python 2.6

### PR DESCRIPTION
**Pull request by aaylward**
This adds support for python 2.6. All tests pass in py26 and py27.

### CODE REVIEW

**Comment by tals** [comment]
Oh, this is really nice! Thanks!

**Comment by aaylward** [comment]
Thanks for merging! Is it easy to get travis to test against python2.6 so that future changes don't revert support?

**Comment by tals** [comment]
added in 9b3eba5 :)
I'll do a pypi push tonight

**Comment by aaylward** [comment]
awesome. Thanks very much!

**Comment by tals** [comment]
It's up. You can now install it with pip :)

**Comment by aaylward** [comment]
sweet :)

**Pull request merged**
