### PR TITLE
Adding support for proxy servers

### PR DESCRIPTION
**Pull request by venantius**
Our company needs to use proxy servers for some of our deployments -- this pull request adds in proxy support to the BoxClient class. 

Proxy information here should be specified in the same way it normally is for the requests library, e.g.: {'http': 'http://127.0.01', 'https': 'https://127.0.0.1'} for the appropriate server locations.

### CODE REVIEW

**Comment by tals** [comment]
Coolness :)

A few comments:
- Can you please document the "proxies" argument in `__init__()`?
- Please add a test case for the proxies (see test_client.py). Verify that the coverage is still at 100% by running `nosetests`
- What about 322c628? Did you end up going with v2 auth? Would still be cool to be compatible with 2.6 :)

**Comment by venantius** [comment]
Yeah, I'll log some time on it this week and get the documentation in place and the tests set up.

There were some other 2.6 issues that would need to be patched first; also our ops people got us access to a 2.7 install so I just rolled it back.

**Comment by tals** [comment]
Sweet :)

**Comment by venantius** [comment]
Going to kill this since I haven't written anything in Python in a long time. Feel free to revive if you're feeling so inclined.

**Pull request closed without merging**
